pipeline {
    agent any
       tools {
        maven 'maven3.9.6'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                sh "echo git cloning repo"
                git branch: 'main', url: 'https://github.com/michaelkedey/practice-devops-assignments.git'
            }
        }
        
        stage('Build') {
            steps {
                // Change directory to the desired directory within the repository
                dir('practice-web-app/my-app') {
                    // Perform build steps
                    sh "echo  building app"
                    sh 'mvn clean package'
                }
            }
        }
        
        stage('Test') {
            steps {
                // Change directory to the desired directory within the repository
                dir('practice-web-app/my-app') {
                    // Perform test steps
                    sh "echo  running tests"
                    sh 'mvn test'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                 script {
                    withCredentials([usernamePassword(credentialsId: 'tomcat', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        // Use USERNAME and PASSWORD variables securely
                        // For example, you can use them in shell commands or Maven invocations
                        sh "deploy-script.sh --username ${USERNAME} --password ${PASSWORD}"
                    }
                // Change directory to the desired directory within the repository
                dir('practice-web-app/my-app') {
                    // Perform deployment steps
                    // For example, deploy to Tomcat
                    sh "echo  Deploying to Tomcat"
                    sh 'mvn tomcat7:redeploy'
                }
            }
        }

        stage("6. Email Notification"){
            steps{
                sh "echo Email Notification to DevOps Team"
                emailext body: 'The Deployment is Successful', subject: 'Deployment Success', to: 'privatemyk@gmail.com'
        }  
      }
    }
}

